### ISSUE TITLE
Double encoding render error

### ISSUE THREAD

**Issue by freekmurze** [spatie/dnsrecords.io#44]
See: https://twitter.com/bartvanraaij/status/1045607240248565761

This should be fixed.

**Comment by jryd** [comment]
I'll take a look at this now.

**Comment by bartvanraaij** [comment]
@jryd you beat me to it by 16 seconds, lol!
Slight difference in implementation though.
My PR just removes the `htmlentities()` altogether because I assumed the htmlspecialchars-encoding of Blade would be sufficient. Is there any reason to to think otherwise?

**Comment by jryd** [comment]
@bartvanraaij unless I am mistaken, this won't fix the issue? [htmlspecialchars](http://php.net/manual/en/function.htmlspecialchars.php) still performs translation on quotes?

I gave this a whirl in tinker to verify:
![image](https://user-images.githubusercontent.com/13251203/46204995-86c3f280-c362-11e8-8e50-c67f87fd0eac.png)

**Comment by bartvanraaij** [comment]
@jryd 

A single round of encoding is completely fine, because the browser will display `&quot;` as `"`.
The problem was that `htmlentities()` transformed a `"` into `&quot;` and after that `htmlspecialchars()` (inside Blade) transformed that into `&amp;quot;` (see screenshot in my tweet).

See screenshot with my patch applied:
![screenshot 2018-09-28 at 13 32 45](https://user-images.githubusercontent.com/21202865/46206043-0e8a0c80-c323-11e8-97f2-0e7c201b7eb9.png)

**Comment by jryd** [comment]
Ahh yes, I stand corrected. Unless there’s a need to remove any html entities, then I am inclined to agree that your implementation is better.
